### ISSUE TITLE
Please add redis password

### ISSUE THREAD

**Issue by troke12** [RealistikOsu/RealistikPanel#32]
functions.py
`r = redis.Redis(host=UserConfig["RedisHost"], port=UserConfig["RedisPort"], password=UserConfig["RedisPassword"], db=UserConfig["RedisDb"])`
config.py
`"RedisPassword" : "",`

**Comment by RealistikDash** [comment]
Added to development branch, feel free to close the issue now or I will close it myself when it gets merged to master
