### ISSUE TITLE
clan pagination is missing?

### ISSUE THREAD

**Issue by troke12** [RealistikOsu/RealistikPanel#40]
it's show /logs/? because from pagination.html
i think you need to make the pagination like in users.html?

**Comment by RealistikDash** [comment]
Good idea, will try to add it

**Comment by RealistikDash** [comment]
Ok I forgot to take that into account, greatest apologies. I didn't read the issue correctly upon first reply.

**Comment by RealistikDash** [comment]
Solved by commit e0853a8 in dev branch.
