### ISSUE TITLE
Error Webhook

### ISSUE THREAD

**Issue by RealistikDash** [RealistikOsu/RealistikPanel#41]
Add a Discord webhook that will be posted when a panel error occurs.

Suggestion by Astellia.

**Comment by troke12** [comment]
admin log too maybe?

**Comment by RealistikDash** [comment]
sure

**Comment by RealistikDash** [comment]
![image](https://user-images.githubusercontent.com/36131887/84541873-2fa9b100-acf0-11ea-9faf-e49b7d12eb52.png)
Alright it is done
