### ISSUE TITLE
missing pip module(s) version(s) in requirements.txt

### ISSUE THREAD

**Issue by Uniminin** [RealistikOsu/RealistikPanel#57]
(https://raw.githubusercontent.com/RealistikOsu/RealistikPanel/master/requirements.txt)

It's better to specify what python module versions to pull instead of pulling the latest version. 
Things may not work depending on the module versions used on/for development and the latest one used by user(s).

# To avoid such issues it is strongly recommended to specify all module versions.
# Note That: pip doesn’t have true dependency resolution.

**Comment by RealistikDash** [comment]
This has been done in the development branch (https://github.com/RealistikOsu/RealistikPanel/blob/development/requirements.txt) which will be merged with the master brancho soon
