### ISSUE TITLE
Sorting the beatmap requests by mode

### ISSUE THREAD

**Issue by troke12** [RealistikOsu/RealistikPanel#60]
is that possible to sort beatmap requests by mode?

**Comment by RealistikDash** [comment]
Can be, can you explain a bit more on how that would work?

**Comment by troke12** [comment]
same as like in old-frontend requests
![img](https://cdn.discordapp.com/attachments/408950289962369025/748541459661062194/unknown.png)

**Comment by RealistikDash** [comment]
ah sure

**Comment by lenforiee** [comment]
added in f87544b

**Comment by 7ez** [comment]
only took 3 years!

**Comment by troke12** [comment]
well nice 😁

**Comment by 7ez** [comment]
:trollface:
